services:
  langflow:
    image: langflowai/langflow
    container_name: langflow
    ports:
      - "7860:7860"
    environment:
      DATABASE_URL: postgresql://postgres:[your_postgres_password]@db:5432/[your_postgres_db]
    depends_on:
      - db

  db:
    image: supabase/postgres:15.1.1.78
    container_name: supabase_db
    environment:
      POSTGRES_PASSWORD: your_postgres_password
      POSTGRES_DB: your_postgres_db
    ports:
      - "5432:5432"
    volumes:
      - supabase_data:/var/lib/postgresql/data

  studio:
    image: supabase/studio:latest
    container_name: supabase_studio
    ports:
      - "3000:3000"
    environment:
      SUPABASE_DB_URL: postgresql://postgres:[your_postgres_password]@db:5432/[your_postgres_db]
      SUPABASE_URL: http://localhost:3000
    depends_on:
      - db

  kong:
    image: kong:latest
    container_name: kong
    ports:
      - "8000:8000"
      - "8001:8001"
    environment:
      KONG_DATABASE: "off"
      KONG_PROXY_LISTEN: "0.0.0.0:8000"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    depends_on:
      - db

volumes:
  supabase_data:
