version: '3.8'

services:
  # Langflow Service
  langflow:
    container_name: langflow
    image: langflowai/langflow:latest
    restart: unless-stopped
    environment:
      PORT: ${LANGFLOW_PORT}
      DATABASE_URL: ${LANGFLOW_DATABASE_URL}  # Use the value from the .env file
    ports:
      - "${LANGFLOW_PORT}:${LANGFLOW_PORT}"
    volumes:
      - ./volumes/langflow:/app/data  # Ensure persistent data for Langflow
    depends_on:
      - db  # Make sure Langflow waits for the db service

  # Supabase Studio
  studio:
    container_name: supabase-studio
    image: supabase/studio:20240923-2e3e90c
    restart: unless-stopped
    ports:
      - "3000:3000"
    depends_on:
      - db
      - kong
    environment:
      STUDIO_PG_META_URL: http://meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      SUPABASE_URL: http://kong:8000
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}
      AUTH_JWT_SECRET: ${JWT_SECRET}

  # Kong Gateway for Supabase
  kong:
    container_name: supabase-kong
    image: kong:2.8.1
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8443:8443"
    depends_on:
      - db
    environment:
      KONG_DATABASE: "off"
      SUPABASE_ANON_KEY: ${ANON_KEY}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY}

  # Supabase PostgreSQL Database
  db:
    container_name: supabase-db
    image: supabase/postgres:15.1.1.78
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./volumes/db:/var/lib/postgresql/data  # Persistent storage for DB

volumes:
  db:
  langflow:
